# Utiliser l'image Node.js pour builder le frontend
FROM node:16

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers du projet
COPY frontend/ /app/

# Installer les dépendances
RUN npm install

# Compiler l'application React
RUN npm run build

# Utiliser une image nginx pour servir l'application React
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Exposer le port 80 pour React
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
