version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  python-app:
    build: .
    container_name: python-app
    depends_on:
      - mongo
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react-app
    depends_on:
      - python-app
    ports:
      - "3000:80"

volumes:
  mongo-data:
 